# Generated by Django 4.2.7 on 2023-12-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Failure_сategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_title', models.CharField(max_length=35, unique=True, verbose_name='Причина остановки')),
            ],
            options={
                'verbose_name': 'категория остановки',
                'verbose_name_plural': 'Категории останвоки',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Парк')),
            ],
            options={
                'verbose_name': 'парк',
                'verbose_name_plural': 'Парки',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Модель')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='park', to='filling.park')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(max_length=10, unique=True, verbose_name='Гос.номер')),
                ('eo', models.IntegerField(unique=True, verbose_name='ЕО')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='model', to='filling.sample')),
            ],
            options={
                'verbose_name': 'транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Введите описание случая', verbose_name='Описание')),
                ('time_startstamp', models.DateTimeField(help_text='Выберите время остановки', verbose_name='Время начала')),
                ('time_endstamp', models.DateTimeField(blank=True, help_text='Выберите фактическое время завершения ремонта', null=True, verbose_name='Время окончания')),
                ('failure', models.ForeignKey(help_text='Укажите одну из основных причин остановки ТС', on_delete=django.db.models.deletion.SET, related_name='failure', to='filling.failure_сategory', verbose_name='Причина остановки')),
                ('state_number', models.ForeignKey(help_text='Введите гос. номер ТС', on_delete=django.db.models.deletion.SET, related_name='st_num', to='filling.equip', verbose_name='Гос.номер')),
            ],
            options={
                'verbose_name': 'простой',
                'verbose_name_plural': 'Простои',
            },
        ),
    ]
