# Generated by Django 4.2.7 on 2023-12-08 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации'),
            preserve_default=False,
        ),
    ]
